### ISSUE TITLE
Connect Order History to DB and test services and controllers

### ISSUE THREAD

**Issue by nicole427** [nicole427/ePharmacyDeliverySystem#205]
Make changes to the entity to for JPA to read entity as a table in DB and mark the primary keys
Test Controller
Change repository interface to JPA repository interface.
Connect the entity to DB.
Add business logic where needed

**Comment by amahlathini** [comment]
- Altered the OrderHistory entity for JPA to read entity as a table in DB with primary keys
- Tested OrderHistory Service and Controller
- Changed repository interface to JPA repository interface.
- Connected the entity to DB successfully.
- Added business logic where needed
