### ISSUE TITLE
Connect Order Entity to DB and test services and controllers

### ISSUE THREAD

**Issue by nicole427** [nicole427/ePharmacyDeliverySystem#209]
Make changes to the entity to for JPA to read entity as a table in DB and mark the primary keys
Test Controller
Change repository interface to JPA repository interface.
Connect the entity to DB.
Add business logic where needed

**Comment by amahlathini** [comment]
- Altered the Order entity for JPA to read entity as a table in DB with primary keys
- Tested Order Service and Controller
- Changed createOrder parameters from the OrderFactory to accept items in order place order 
- Changed repository interface to JPA repository interface.
- Connected the entity to DB successfully.
- Added business logic where needed
