### ISSUE TITLE
Create Pharmacy Catalogue Entity

### ISSUE THREAD

**Issue by nicole427** [nicole427/ePharmacyDeliverySystem#3]
Create PharmacyCatalogue entity  that stores the information of the specific catalogue of each pharmacy.
Remember to add comments at the top that will include author, desc, date.
Remember to describe the relation of this entity with others if there is any.
Please follow the correct naming conventions used in our uml diagram.
Do not copy my work but use it as a guideline for builder pattern.
Fork from the groupCollaborationBranch.

**Comment by nelsonmpyana** [comment]
Pharmacy Catalogue is complete

**Comment by nicole427** [comment]
Pharmacy Catalogue entity completed
