### ISSUE TITLE
Create Catalogue Item Entity

### ISSUE THREAD

**Issue by nicole427** [nicole427/ePharmacyDeliverySystem#4]
Create Catalogue Item Entity that stores the information of each catalogue item.
Remember to add comments at the top that will include author, desc, date.
Remember to describe the relation of this entity with others if there is any.
Please follow the correct naming conventions used in our uml diagram.
Do not copy my work but use it as a guideline for builder pattern.
Fork from the groupCollaborationBranch.

**Comment by nelsonmpyana** [comment]
Completed the Item Catalogue Entity
