### ISSUE TITLE
Create Payment Entity

### ISSUE THREAD

**Issue by nicole427** [nicole427/ePharmacyDeliverySystem#7]
Create Payment Entity  that stores the information of each order payment a user is making.
Remember to add comments at the top that will include author, desc, date.
Remember to describe the relation of this entity with others if there is any.
Please follow the correct naming conventions used in our uml diagram.
Do not copy my work but use it as a guideline for builder pattern.
Fork from the groupCollaborationBranch.

**Comment by amahlathini** [comment]
Payment Entity Created
