### ISSUE TITLE
Create Medical Aid Repository & Test

### ISSUE THREAD

**Issue by nicole427** [nicole427/ePharmacyDeliverySystem#71]
Create medical aid repository class with relevant implementation interfaces and test.

**Comment by nicole427** [comment]
Opatile Kelobang successfuly completed this issue.

**Comment by OpatileKelobang** [comment]
Fixed MedicalAidRepositoryImplTest.java run order

**Comment by OpatileKelobang** [comment]
Fixed MedicalAidRepositoryImplTest.java run order (deleted method was running before get all)
